#!/bin/bash
sudo sed -i -E 's/^#?PermitRootLogin.*/PermitRootLogin no/; s/^#?PasswordAuthentication.*/PasswordAuthentication no/; s/^#?PermitEmptyPasswords.*/PermitEmptyPasswords no/; s/^#?PubkeyAuthentication.*/PubkeyAuthentication yes/; s/^#?X11Forwarding.*/X11Forwarding no/; s/^#?Protocol.*/Protocol 2/' /etc/ssh/sshd_config
